GOOGLE_API_KEY = "AIzaSyDR0tlb2880Sks4bmoSJ9M3EFIEn-eF1zM"
TELEGRAM_BOT_TOKEN = "8006309759:AAGvUdRRCLkhSqekiNhwzhJCi4lVcHsLJi4"


SPOTIPY_CLIENT_ID = "1475377d5d044ad1b404160f0738c1ce"
SPOTIPY_CLIENT_SECRET = "7027f1458f7b47e694c2327729cf8df2"
SPOTIPY_REDIRECT_URI = "https://3lpaujkvrbcdbrjvtdsg6j.streamlit.app"